### ISSUE TITLE
Useklé logo K-SCUK v záhlaví

### ISSUE THREAD

**Issue by horacekj** [zverinec/kscuk-web-restyle#2]
Logo v záhlaví je useklé. Podle velikosti okna prohlížeče jednou horizontálně a jenou vertikálně.

![screenshot_20180306_225536](https://user-images.githubusercontent.com/12673442/37060766-8bfeefde-2191-11e8-9f1d-73128651ed89.png)

**Comment by zvizesna** [comment]
Oukej.

Sháním geniální nápady ohledně toho, jak rozumně zasadit průhledný obrázek do jinak neprůhledného menu, tak, aby pod ním byla vidět úvodní fotka.

**Comment by horacekj** [comment]
> Sháním geniální nápady ohledně toho, jak rozumně zasadit průhledný obrázek do jinak neprůhledného menu, tak, aby pod ním byla vidět úvodní fotka.

Je otázka, jestli má to průhledné pozadí u "K" vážně smysl. Na schůzi jsme to diskutovali. Pokud je to technicky náročné, není lepší průhledné K oželet? @Krejdom
