### ISSUE TITLE
Bílý pruh mezi záhlaví a fotkou je (někdy) rušivý

### ISSUE THREAD

**Issue by horacekj** [zverinec/kscuk-web-restyle#3]
Posunout pruh? Nebo odstranit úplně?

![screenshot_20180306_225719](https://user-images.githubusercontent.com/12673442/37060827-c275397e-2191-11e8-91ca-282732b5a00f.png)

**Comment by zvizesna** [comment]
Někdy myšleno tehdy, když se takhle rozbije stránka?
Tato verze zatím není responzivní.
Návrh je k dispozici pro zkoušení různých variant. Osobně preferuju varianty s pruhem, protože mi nestačí kontrasty mezi fotkou a menu, potažmo fotkou a separátorem (ten obzvlášť splývá s trávou), a připadá mi to s pruhy takové upravenější.

**Comment by horacekj** [comment]
Na jakou šířku si mám stránku zobrazit, abych byla taková, jakou ji chceš ty?

**Comment by zvizesna** [comment]
Tohle je tvá plná velikost? V tom případě jsem to podcenila. :D Zkus simulovat 1920x1080.
